extra:
  footer: Created by [Rosie](https://github.com/PBOwner) with <3
nav:
- Home: index.md
- TimeoutSelf: TimeoutSelf.md
site_name: TimeoutSelf's Documentation
site_url: https://docs.prismbot.icu/TimeoutSelf/
theme:
  name: dracula
use_directory_urls: false
