extra:
  footer: Created by [Rosie](https://github.com/PBOwner) with <3
nav:
- Home: index.md
- RestartMsg: RestartMsg.md
site_name: RestartMsg's Documentation
site_url: https://docs.prismbot.icu/RestartMsg/
theme:
  name: dracula
use_directory_urls: false
