extra:
  footer: Created by [Rosie](https://github.com/PBOwner) with <3
nav:
- Home: index.md
- MultiCommands: MultiCommands.md
site_name: MultiCommands's Documentation
site_url: https://docs.prismbot.icu/MultiCommands/
theme:
  name: dracula
use_directory_urls: false
