extra:
  footer: Created by [Rosie](https://github.com/PBOwner) with <3
nav:
- Home: index.md
- Filter: Filter.md
site_name: Filter's Documentation
site_url: https://docs.prismbot.icu/Filter/
theme:
  name: dracula
use_directory_urls: false
