extra:
  footer: Created by [Rosie](https://github.com/PBOwner) with <3
nav:
- Home: index.md
- IsItDown: IsItDown.md
site_name: IsItDown's Documentation
site_url: https://docs.prismbot.icu/IsItDown/
theme:
  name: dracula
use_directory_urls: false
