extra:
  footer: Created by [Rosie](https://github.com/PBOwner) with <3
nav:
- Home: index.md
- RoleRequests: RoleRequests.md
site_name: RoleRequests's Documentation
site_url: https://docs.prismbot.icu/RoleRequests/
theme:
  name: dracula
use_directory_urls: false
