extra:
  footer: Created by [Rosie](https://github.com/PBOwner) with <3
nav:
- Home: index.md
- AntiLinks: AntiLinks.md
site_name: AntiLinks's Documentation
site_url: https://docs.prismbot.icu/AntiLinks/
theme:
  name: dracula
use_directory_urls: false
