extra:
  footer: Created by [Rosie](https://github.com/PBOwner) with <3
nav:
- Home: index.md
- LinkQuoter: LinkQuoter.md
site_name: LinkQuoter's Documentation
site_url: https://docs.prismbot.icu/LinkQuoter/
theme:
  name: dracula
use_directory_urls: false
