extra:
  footer: Created by [Rosie](https://github.com/PBOwner) with <3
nav:
- Home: index.md
- RoleTools: RoleTools.md
site_name: RoleTools's Documentation
site_url: https://docs.prismbot.icu/RoleTools/
theme:
  name: dracula
use_directory_urls: false
