extra:
  footer: Created by [Rosie](https://github.com/PBOwner) with <3
nav:
- Home: index.md
- ClearChannel: ClearChannel.md
site_name: ClearChannel's Documentation
site_url: https://docs.prismbot.icu/ClearChannel/
theme:
  name: dracula
use_directory_urls: false
