extra:
  footer: Created by [Rosie](https://github.com/PBOwner) with <3
nav:
- Home: index.md
- ModManager: ModManager.md
site_name: ModManager's Documentation
site_url: https://docs.prismbot.icu/ModManager/
theme:
  name: dracula
use_directory_urls: false
