extra:
  footer: Created by [Rosie](https://github.com/PBOwner) with <3
nav:
- Home: index.md
- Shell: Shell.md
site_name: Shell's Documentation
site_url: https://docs.prismbot.icu/Shell/
theme:
  name: dracula
use_directory_urls: false
