extra:
  footer: Created by [Rosie](https://github.com/PBOwner) with <3
nav:
- Home: index.md
- Trivia: Trivia.md
site_name: Trivia's Documentation
site_url: https://docs.prismbot.icu/Trivia/
theme:
  name: dracula
use_directory_urls: false
