extra:
  footer: Created by [Rosie](https://github.com/PBOwner) with <3
nav:
- Home: index.md
- Perform: Perform.md
site_name: Perform's Documentation
site_url: https://docs.prismbot.icu/Perform/
theme:
  name: dracula
use_directory_urls: false
