extra:
  footer: Created by [Rosie](https://github.com/PBOwner) with <3
nav:
- Home: index.md
- Pingtime: Pingtime.md
site_name: Pingtime's Documentation
site_url: https://docs.prismbot.icu/Pingtime/
theme:
  name: dracula
use_directory_urls: false
