extra:
  footer: Created by [Rosie](https://github.com/PBOwner) with <3
nav:
- Home: index.md
- Index: Index.md
site_name: Index's Documentation
site_url: https://docs.prismbot.icu/Index/
theme:
  name: dracula
use_directory_urls: false
