extra:
  footer: Created by [Rosie](https://github.com/PBOwner) with <3
nav:
- Home: index.md
- RoleBoards: RoleBoards.md
site_name: RoleBoards's Documentation
site_url: https://docs.prismbot.icu/RoleBoards/
theme:
  name: dracula
use_directory_urls: false
