extra:
  footer: Created by [Rosie](https://github.com/PBOwner) with <3
nav:
- Home: index.md
- AAA3A_utils: AAA3A_utils.md
site_name: AAA3A_utils's Documentation
site_url: https://docs.prismbot.icu/AAA3A_utils/
theme:
  name: dracula
use_directory_urls: false
