extra:
  footer: Created by [Rosie](https://github.com/PBOwner) with <3
nav:
- Home: index.md
- NoNuke: NoNuke.md
site_name: NoNuke's Documentation
site_url: https://docs.prismbot.icu/NoNuke/
theme:
  name: dracula
use_directory_urls: false
