extra:
  footer: Created by [Rosie](https://github.com/PBOwner) with <3
nav:
- Home: index.md
- Simulator: Simulator.md
site_name: Simulator's Documentation
site_url: https://docs.prismbot.icu/Simulator/
theme:
  name: dracula
use_directory_urls: false
