extra:
  footer: Created by [Rosie](https://github.com/PBOwner) with <3
nav:
- Home: index.md
- Activities: Activities.md
site_name: Activities's Documentation
site_url: https://docs.prismbot.icu/Activities/
theme:
  name: dracula
use_directory_urls: false
