extra:
  footer: Created by [Rosie](https://github.com/PBOwner) with <3
nav:
- Home: index.md
- UrlButtons: UrlButtons.md
site_name: UrlButtons's Documentation
site_url: https://docs.prismbot.icu/UrlButtons/
theme:
  name: dracula
use_directory_urls: false
