extra:
  footer: Created by [Rosie](https://github.com/PBOwner) with <3
nav:
- Home: index.md
- GlobalBan: GlobalBan.md
site_name: GlobalBan's Documentation
site_url: https://docs.prismbot.icu/GlobalBan/
theme:
  name: dracula
use_directory_urls: false
