extra:
  footer: Created by [Rosie](https://github.com/PBOwner) with <3
nav:
- Home: index.md
- Sticky: Sticky.md
site_name: Sticky's Documentation
site_url: https://docs.prismbot.icu/Sticky/
theme:
  name: dracula
use_directory_urls: false
