extra:
  footer: Created by [Rosie](https://github.com/PBOwner) with <3
nav:
- Home: index.md
- CodeSnippets: CodeSnippets.md
site_name: CodeSnippets's Documentation
site_url: https://docs.prismbot.icu/CodeSnippets/
theme:
  name: dracula
use_directory_urls: false
