extra:
  footer: Created by [Rosie](https://github.com/PBOwner) with <3
nav:
- Home: index.md
- Pinboard: Pinboard.md
site_name: Pinboard's Documentation
site_url: https://docs.prismbot.icu/Pinboard/
theme:
  name: dracula
use_directory_urls: false
