extra:
  footer: Created by [Rosie](https://github.com/PBOwner) with <3
nav:
- Home: index.md
- SimpleSanction: SimpleSanction.md
site_name: SimpleSanction's Documentation
site_url: https://docs.prismbot.icu/SimpleSanction/
theme:
  name: dracula
use_directory_urls: false
