extra:
  footer: Created by [Rosie](https://github.com/PBOwner) with <3
nav:
- Home: index.md
- SlowMode: SlowMode.md
site_name: SlowMode's Documentation
site_url: https://docs.prismbot.icu/SlowMode/
theme:
  name: dracula
use_directory_urls: false
