extra:
  footer: Created by [Rosie](https://github.com/PBOwner) with <3
nav:
- Home: index.md
- HostInfo: HostInfo.md
site_name: HostInfo's Documentation
site_url: https://docs.prismbot.icu/HostInfo/
theme:
  name: dracula
use_directory_urls: false
