extra:
  footer: Created by [Rosie](https://github.com/PBOwner) with <3
nav:
- Home: index.md
- eep: eep.md
site_name: eep's Documentation
site_url: https://docs.prismbot.icu/eep/
theme:
  name: dracula
use_directory_urls: false
