extra:
  footer: Created by [Rosie](https://github.com/PBOwner) with <3
nav:
- Home: index.md
- BoostUtils: BoostUtils.md
site_name: BoostUtils's Documentation
site_url: https://docs.prismbot.icu/BoostUtils/
theme:
  name: dracula
use_directory_urls: false
