extra:
  footer: Created by [Rosie](https://github.com/PBOwner) with <3
nav:
- Home: index.md
- ImageScanner: ImageScanner.md
site_name: ImageScanner's Documentation
site_url: https://docs.prismbot.icu/ImageScanner/
theme:
  name: dracula
use_directory_urls: false
