extra:
  footer: Created by [Rosie](https://github.com/PBOwner) with <3
nav:
- Home: index.md
- RandomEmoji: RandomEmoji.md
site_name: RandomEmoji's Documentation
site_url: https://docs.prismbot.icu/RandomEmoji/
theme:
  name: dracula
use_directory_urls: false
