extra:
  footer: Created by [Rosie](https://github.com/PBOwner) with <3
nav:
- Home: index.md
- PyPi: PyPi.md
site_name: PyPi's Documentation
site_url: https://docs.prismbot.icu/PyPi/
theme:
  name: dracula
use_directory_urls: false
