extra:
  footer: Created by [Rosie](https://github.com/PBOwner) with <3
nav:
- Home: index.md
- Hellohook: Hellohook.md
site_name: Hellohook's Documentation
site_url: https://docs.prismbot.icu/Hellohook/
theme:
  name: dracula
use_directory_urls: false
