extra:
  footer: Created by [Rosie](https://github.com/PBOwner) with <3
nav:
- Home: index.md
- RolesButtons: RolesButtons.md
site_name: RolesButtons's Documentation
site_url: https://docs.prismbot.icu/RolesButtons/
theme:
  name: dracula
use_directory_urls: false
