extra:
  footer: Created by [Rosie](https://github.com/PBOwner) with <3
nav:
- Home: index.md
- Quiz: Quiz.md
site_name: Quiz's Documentation
site_url: https://docs.prismbot.icu/Quiz/
theme:
  name: dracula
use_directory_urls: false
