extra:
  footer: Created by [Rosie](https://github.com/PBOwner) with <3
nav:
- Home: index.md
- FIFO: FIFO.md
site_name: FIFO's Documentation
site_url: https://docs.prismbot.icu/FIFO/
theme:
  name: dracula
use_directory_urls: false
