extra:
  footer: Created by [Rosie](https://github.com/PBOwner) with <3
nav:
- Home: index.md
- Giveaways: Giveaways.md
site_name: Giveaways's Documentation
site_url: https://docs.prismbot.icu/Giveaways/
theme:
  name: dracula
use_directory_urls: false
