extra:
  footer: Created by [Rosie](https://github.com/PBOwner) with <3
nav:
- Home: index.md
- HidePing: HidePing.md
site_name: HidePing's Documentation
site_url: https://docs.prismbot.icu/HidePing/
theme:
  name: dracula
use_directory_urls: false
