extra:
  footer: Created by [Rosie](https://github.com/PBOwner) with <3
nav:
- Home: index.md
- ReviewsCog: ReviewsCog.md
site_name: ReviewsCog's Documentation
site_url: https://docs.prismbot.icu/ReviewsCog/
theme:
  name: dracula
use_directory_urls: false
