extra:
  footer: Created by [Rosie](https://github.com/PBOwner) with <3
nav:
- Home: index.md
- Lenny: Lenny.md
site_name: Lenny's Documentation
site_url: https://docs.prismbot.icu/Lenny/
theme:
  name: dracula
use_directory_urls: false
