extra:
  footer: Created by [Rosie](https://github.com/PBOwner) with <3
nav:
- Home: index.md
- Backup: Backup.md
site_name: Backup's Documentation
site_url: https://docs.prismbot.icu/Backup/
theme:
  name: dracula
use_directory_urls: false
