extra:
  footer: Created by [Rosie](https://github.com/PBOwner) with <3
nav:
- Home: index.md
- Verifyer: Verifyer.md
site_name: Verifyer's Documentation
site_url: https://docs.prismbot.icu/Verifyer/
theme:
  name: dracula
use_directory_urls: false
