extra:
  footer: Created by [Rosie](https://github.com/PBOwner) with <3
nav:
- Home: index.md
- AntiSpam: AntiSpam.md
site_name: AntiSpam's Documentation
site_url: https://docs.prismbot.icu/AntiSpam/
theme:
  name: dracula
use_directory_urls: false
