extra:
  footer: Created by [Rosie](https://github.com/PBOwner) with <3
nav:
- Home: index.md
- AddImage: AddImage.md
site_name: AddImage's Documentation
site_url: https://docs.prismbot.icu/AddImage/
theme:
  name: dracula
use_directory_urls: false
