extra:
  footer: Created by [Rosie](https://github.com/PBOwner) with <3
nav:
- Home: index.md
- Reports: Reports.md
site_name: Reports's Documentation
site_url: https://docs.prismbot.icu/Reports/
theme:
  name: dracula
use_directory_urls: false
