extra:
  footer: Created by [Rosie](https://github.com/PBOwner) with <3
nav:
- Home: index.md
- ExtendedEconomy: ExtendedEconomy.md
site_name: ExtendedEconomy's Documentation
site_url: https://docs.prismbot.icu/ExtendedEconomy/
theme:
  name: dracula
use_directory_urls: false
