extra:
  footer: Created by [Rosie](https://github.com/PBOwner) with <3
nav:
- Home: index.md
- Trigger: Trigger.md
site_name: Trigger's Documentation
site_url: https://docs.prismbot.icu/Trigger/
theme:
  name: dracula
use_directory_urls: false
