extra:
  footer: Created by [Rosie](https://github.com/PBOwner) with <3
nav:
- Home: index.md
- WelcomeCount: WelcomeCount.md
site_name: WelcomeCount's Documentation
site_url: https://docs.prismbot.icu/WelcomeCount/
theme:
  name: dracula
use_directory_urls: false
