extra:
  footer: Created by [Rosie](https://github.com/PBOwner) with <3
nav:
- Home: index.md
- RequestGB: RequestGB.md
site_name: RequestGB's Documentation
site_url: https://docs.prismbot.icu/RequestGB/
theme:
  name: dracula
use_directory_urls: false
