extra:
  footer: Created by [Rosie](https://github.com/PBOwner) with <3
nav:
- Home: index.md
- COC: COC.md
site_name: COC's Documentation
site_url: https://docs.prismbot.icu/COC/
theme:
  name: dracula
use_directory_urls: false
