extra:
  footer: Created by [Rosie](https://github.com/PBOwner) with <3
nav:
- Home: index.md
- StickyMember: StickyMember.md
site_name: StickyMember's Documentation
site_url: https://docs.prismbot.icu/StickyMember/
theme:
  name: dracula
use_directory_urls: false
