extra:
  footer: Created by [Rosie](https://github.com/PBOwner) with <3
nav:
- Home: index.md
- IntroCog: IntroCog.md
site_name: IntroCog's Documentation
site_url: https://docs.prismbot.icu/IntroCog/
theme:
  name: dracula
use_directory_urls: false
