extra:
  footer: Created by [Rosie](https://github.com/PBOwner) with <3
nav:
- Home: index.md
- ExclusiveRoles: ExclusiveRoles.md
site_name: ExclusiveRoles's Documentation
site_url: https://docs.prismbot.icu/ExclusiveRoles/
theme:
  name: dracula
use_directory_urls: false
