extra:
  footer: Created by [Rosie](https://github.com/PBOwner) with <3
nav:
- Home: index.md
- BanChart: BanChart.md
site_name: BanChart's Documentation
site_url: https://docs.prismbot.icu/BanChart/
theme:
  name: dracula
use_directory_urls: false
