extra:
  footer: Created by [Rosie](https://github.com/PBOwner) with <3
nav:
- Home: index.md
- JoinPing: JoinPing.md
site_name: JoinPing's Documentation
site_url: https://docs.prismbot.icu/JoinPing/
theme:
  name: dracula
use_directory_urls: false
