extra:
  footer: Created by [Rosie](https://github.com/PBOwner) with <3
nav:
- Home: index.md
- EconomyTrickle: EconomyTrickle.md
site_name: EconomyTrickle's Documentation
site_url: https://docs.prismbot.icu/EconomyTrickle/
theme:
  name: dracula
use_directory_urls: false
