extra:
  footer: Created by [Rosie](https://github.com/PBOwner) with <3
nav:
- Home: index.md
- Bumper: Bumper.md
site_name: Bumper's Documentation
site_url: https://docs.prismbot.icu/Bumper/
theme:
  name: dracula
use_directory_urls: false
