extra:
  footer: Created by [Rosie](https://github.com/PBOwner) with <3
nav:
- Home: index.md
- Core: Core.md
site_name: Core's Documentation
site_url: https://docs.prismbot.icu/Core/
theme:
  name: dracula
use_directory_urls: false
