extra:
  footer: Created by [Rosie](https://github.com/PBOwner) with <3
nav:
- Home: index.md
- Fluent: Fluent.md
site_name: Fluent's Documentation
site_url: https://docs.prismbot.icu/Fluent/
theme:
  name: dracula
use_directory_urls: false
