extra:
  footer: Created by [Rosie](https://github.com/PBOwner) with <3
nav:
- Home: index.md
- AdWarn: AdWarn.md
site_name: AdWarn's Documentation
site_url: https://docs.prismbot.icu/AdWarn/
theme:
  name: dracula
use_directory_urls: false
