extra:
  footer: Created by [Rosie](https://github.com/PBOwner) with <3
nav:
- Home: index.md
- InstaDelete: InstaDelete.md
site_name: InstaDelete's Documentation
site_url: https://docs.prismbot.icu/InstaDelete/
theme:
  name: dracula
use_directory_urls: false
