extra:
  footer: Created by [Rosie](https://github.com/PBOwner) with <3
nav:
- Home: index.md
- Aliases: Aliases.md
site_name: Aliases's Documentation
site_url: https://docs.prismbot.icu/Aliases/
theme:
  name: dracula
use_directory_urls: false
