extra:
  footer: Created by [Rosie](https://github.com/PBOwner) with <3
nav:
- Home: index.md
- Talk: Talk.md
site_name: Talk's Documentation
site_url: https://docs.prismbot.icu/Talk/
theme:
  name: dracula
use_directory_urls: false
