extra:
  footer: Created by [Rosie](https://github.com/PBOwner) with <3
nav:
- Home: index.md
- Downloader: Downloader.md
site_name: Downloader's Documentation
site_url: https://docs.prismbot.icu/Downloader/
theme:
  name: dracula
use_directory_urls: false
