extra:
  footer: Created by [Rosie](https://github.com/PBOwner) with <3
nav:
- Home: index.md
- AutoDocs: AutoDocs.md
site_name: AutoDocs's Documentation
site_url: https://docs.prismbot.icu/AutoDocs/
theme:
  name: dracula
use_directory_urls: false
