extra:
  footer: Created by [Rosie](https://github.com/PBOwner) with <3
nav:
- Home: index.md
- Roomer: Roomer.md
site_name: Roomer's Documentation
site_url: https://docs.prismbot.icu/Roomer/
theme:
  name: dracula
use_directory_urls: false
