extra:
  footer: Created by [Rosie](https://github.com/PBOwner) with <3
nav:
- Home: index.md
- SelfAssign: SelfAssign.md
site_name: SelfAssign's Documentation
site_url: https://docs.prismbot.icu/SelfAssign/
theme:
  name: dracula
use_directory_urls: false
