extra:
  footer: Created by [Rosie](https://github.com/PBOwner) with <3
nav:
- Home: index.md
- Skyrim: Skyrim.md
site_name: Skyrim's Documentation
site_url: https://docs.prismbot.icu/Skyrim/
theme:
  name: dracula
use_directory_urls: false
