extra:
  footer: Created by [Rosie](https://github.com/PBOwner) with <3
nav:
- Home: index.md
- RoleUtils: RoleUtils.md
site_name: RoleUtils's Documentation
site_url: https://docs.prismbot.icu/RoleUtils/
theme:
  name: dracula
use_directory_urls: false
