extra:
  footer: Created by [Rosie](https://github.com/PBOwner) with <3
nav:
- Home: index.md
- Economy: Economy.md
site_name: Economy's Documentation
site_url: https://docs.prismbot.icu/Economy/
theme:
  name: dracula
use_directory_urls: false
