extra:
  footer: Created by [Rosie](https://github.com/PBOwner) with <3
nav:
- Home: index.md
- ChessGame: ChessGame.md
site_name: ChessGame's Documentation
site_url: https://docs.prismbot.icu/ChessGame/
theme:
  name: dracula
use_directory_urls: false
