extra:
  footer: Created by [Rosie](https://github.com/PBOwner) with <3
nav:
- Home: index.md
- AutoGist: AutoGist.md
site_name: AutoGist's Documentation
site_url: https://docs.prismbot.icu/AutoGist/
theme:
  name: dracula
use_directory_urls: false
