extra:
  footer: Created by [Rosie](https://github.com/PBOwner) with <3
nav:
- Home: index.md
- PartyCrash: PartyCrash.md
site_name: PartyCrash's Documentation
site_url: https://docs.prismbot.icu/PartyCrash/
theme:
  name: dracula
use_directory_urls: false
