extra:
  footer: Created by [Rosie](https://github.com/PBOwner) with <3
nav:
- Home: index.md
- System: System.md
site_name: System's Documentation
site_url: https://docs.prismbot.icu/System/
theme:
  name: dracula
use_directory_urls: false
