extra:
  footer: Created by [Rosie](https://github.com/PBOwner) with <3
nav:
- Home: index.md
- RepoList: RepoList.md
site_name: RepoList's Documentation
site_url: https://docs.prismbot.icu/RepoList/
theme:
  name: dracula
use_directory_urls: false
