extra:
  footer: Created by [Rosie](https://github.com/PBOwner) with <3
nav:
- Home: index.md
- Strikes: Strikes.md
site_name: Strikes's Documentation
site_url: https://docs.prismbot.icu/Strikes/
theme:
  name: dracula
use_directory_urls: false
