extra:
  footer: Created by [Rosie](https://github.com/PBOwner) with <3
nav:
- Home: index.md
- AutoTraceback: AutoTraceback.md
site_name: AutoTraceback's Documentation
site_url: https://docs.prismbot.icu/AutoTraceback/
theme:
  name: dracula
use_directory_urls: false
