extra:
  footer: Created by [Rosie](https://github.com/PBOwner) with <3
nav:
- Home: index.md
- Counter: Counter.md
site_name: Counter's Documentation
site_url: https://docs.prismbot.icu/Counter/
theme:
  name: dracula
use_directory_urls: false
