extra:
  footer: Created by [Rosie](https://github.com/PBOwner) with <3
nav:
- Home: index.md
- DontPingStaff: DontPingStaff.md
site_name: DontPingStaff's Documentation
site_url: https://docs.prismbot.icu/DontPingStaff/
theme:
  name: dracula
use_directory_urls: false
