extra:
  footer: Created by [Rosie](https://github.com/PBOwner) with <3
nav:
- Home: index.md
- UselessFacts: UselessFacts.md
site_name: UselessFacts's Documentation
site_url: https://docs.prismbot.icu/UselessFacts/
theme:
  name: dracula
use_directory_urls: false
