extra:
  footer: Created by [Rosie](https://github.com/PBOwner) with <3
nav:
- Home: index.md
- RandomTopic: RandomTopic.md
site_name: RandomTopic's Documentation
site_url: https://docs.prismbot.icu/RandomTopic/
theme:
  name: dracula
use_directory_urls: false
