extra:
  footer: Created by [Rosie](https://github.com/PBOwner) with <3
nav:
- Home: index.md
- PhenUtils: PhenUtils.md
site_name: PhenUtils's Documentation
site_url: https://docs.prismbot.icu/PhenUtils/
theme:
  name: dracula
use_directory_urls: false
