extra:
  footer: Created by [Rosie](https://github.com/PBOwner) with <3
nav:
- Home: index.md
- StaffApps: StaffApps.md
site_name: StaffApps's Documentation
site_url: https://docs.prismbot.icu/StaffApps/
theme:
  name: dracula
use_directory_urls: false
