extra:
  footer: Created by [Rosie](https://github.com/PBOwner) with <3
nav:
- Home: index.md
- NickNamer: NickNamer.md
site_name: NickNamer's Documentation
site_url: https://docs.prismbot.icu/NickNamer/
theme:
  name: dracula
use_directory_urls: false
