extra:
  footer: Created by [Rosie](https://github.com/PBOwner) with <3
nav:
- Home: index.md
- EmbedUtils: EmbedUtils.md
site_name: EmbedUtils's Documentation
site_url: https://docs.prismbot.icu/EmbedUtils/
theme:
  name: dracula
use_directory_urls: false
