extra:
  footer: Created by [Rosie](https://github.com/PBOwner) with <3
nav:
- Home: index.md
- FakeMod: FakeMod.md
site_name: FakeMod's Documentation
site_url: https://docs.prismbot.icu/FakeMod/
theme:
  name: dracula
use_directory_urls: false
