extra:
  footer: Created by [Rosie](https://github.com/PBOwner) with <3
nav:
- Home: index.md
- CommandsButtons: CommandsButtons.md
site_name: CommandsButtons's Documentation
site_url: https://docs.prismbot.icu/CommandsButtons/
theme:
  name: dracula
use_directory_urls: false
