extra:
  footer: Created by [Rosie](https://github.com/PBOwner) with <3
nav:
- Home: index.md
- Quarantine: Quarantine.md
site_name: Quarantine's Documentation
site_url: https://docs.prismbot.icu/Quarantine/
theme:
  name: dracula
use_directory_urls: false
