extra:
  footer: Created by [Rosie](https://github.com/PBOwner) with <3
nav:
- Home: index.md
- Badges: Badges.md
site_name: Badges's Documentation
site_url: https://docs.prismbot.icu/Badges/
theme:
  name: dracula
use_directory_urls: false
