extra:
  footer: Created by [Rosie](https://github.com/PBOwner) with <3
nav:
- Home: index.md
- OwnerProtection: OwnerProtection.md
site_name: OwnerProtection's Documentation
site_url: https://docs.prismbot.icu/OwnerProtection/
theme:
  name: dracula
use_directory_urls: false
