extra:
  footer: Created by [Rosie](https://github.com/PBOwner) with <3
nav:
- Home: index.md
- AntiPhishing: AntiPhishing.md
site_name: AntiPhishing's Documentation
site_url: https://docs.prismbot.icu/AntiPhishing/
theme:
  name: dracula
use_directory_urls: false
