extra:
  footer: Created by [Rosie](https://github.com/PBOwner) with <3
nav:
- Home: index.md
- AFK: AFK.md
site_name: AFK's Documentation
site_url: https://docs.prismbot.icu/AFK/
theme:
  name: dracula
use_directory_urls: false
