extra:
  footer: Created by [Rosie](https://github.com/PBOwner) with <3
nav:
- Home: index.md
- SecureInv: SecureInv.md
site_name: SecureInv's Documentation
site_url: https://docs.prismbot.icu/SecureInv/
theme:
  name: dracula
use_directory_urls: false
