extra:
  footer: Created by [Rosie](https://github.com/PBOwner) with <3
nav:
- Home: index.md
- Paginator: Paginator.md
site_name: Paginator's Documentation
site_url: https://docs.prismbot.icu/Paginator/
theme:
  name: dracula
use_directory_urls: false
