extra:
  footer: Created by [Rosie](https://github.com/PBOwner) with <3
nav:
- Home: index.md
- Adventure: Adventure.md
site_name: Adventure's Documentation
site_url: https://docs.prismbot.icu/Adventure/
theme:
  name: dracula
use_directory_urls: false
