extra:
  footer: Created by [Rosie](https://github.com/PBOwner) with <3
nav:
- Home: index.md
- TempRoles: TempRoles.md
site_name: TempRoles's Documentation
site_url: https://docs.prismbot.icu/TempRoles/
theme:
  name: dracula
use_directory_urls: false
