extra:
  footer: Created by [Rosie](https://github.com/PBOwner) with <3
nav:
- Home: index.md
- Encoding: Encoding.md
site_name: Encoding's Documentation
site_url: https://docs.prismbot.icu/Encoding/
theme:
  name: dracula
use_directory_urls: false
