extra:
  footer: Created by [Rosie](https://github.com/PBOwner) with <3
nav:
- Home: index.md
- DiscordSearch: DiscordSearch.md
site_name: DiscordSearch's Documentation
site_url: https://docs.prismbot.icu/DiscordSearch/
theme:
  name: dracula
use_directory_urls: false
