extra:
  footer: Created by [Rosie](https://github.com/PBOwner) with <3
nav:
- Home: index.md
- AnonReporter: AnonReporter.md
site_name: AnonReporter's Documentation
site_url: https://docs.prismbot.icu/AnonReporter/
theme:
  name: dracula
use_directory_urls: false
