extra:
  footer: Created by [Rosie](https://github.com/PBOwner) with <3
nav:
- Home: index.md
- MemberPrefix: MemberPrefix.md
site_name: MemberPrefix's Documentation
site_url: https://docs.prismbot.icu/MemberPrefix/
theme:
  name: dracula
use_directory_urls: false
