extra:
  footer: Created by [Rosie](https://github.com/PBOwner) with <3
nav:
- Home: index.md
- ModLog: ModLog.md
site_name: ModLog's Documentation
site_url: https://docs.prismbot.icu/ModLog/
theme:
  name: dracula
use_directory_urls: false
