extra:
  footer: Created by [Rosie](https://github.com/PBOwner) with <3
nav:
- Home: index.md
- WormHole: WormHole.md
site_name: WormHole's Documentation
site_url: https://docs.prismbot.icu/WormHole/
theme:
  name: dracula
use_directory_urls: false
