extra:
  footer: Created by [Rosie](https://github.com/PBOwner) with <3
nav:
- Home: index.md
- Unbelievaboat: Unbelievaboat.md
site_name: Unbelievaboat's Documentation
site_url: https://docs.prismbot.icu/Unbelievaboat/
theme:
  name: dracula
use_directory_urls: false
