extra:
  footer: Created by [Rosie](https://github.com/PBOwner) with <3
nav:
- Home: index.md
- Events: Events.md
site_name: Events's Documentation
site_url: https://docs.prismbot.icu/Events/
theme:
  name: dracula
use_directory_urls: false
