extra:
  footer: Created by [Rosie](https://github.com/PBOwner) with <3
nav:
- Home: index.md
- Reminders: Reminders.md
site_name: Reminders's Documentation
site_url: https://docs.prismbot.icu/Reminders/
theme:
  name: dracula
use_directory_urls: false
