extra:
  footer: Created by [Rosie](https://github.com/PBOwner) with <3
nav:
- Home: index.md
- LevelUp: LevelUp.md
site_name: LevelUp's Documentation
site_url: https://docs.prismbot.icu/LevelUp/
theme:
  name: dracula
use_directory_urls: false
