extra:
  footer: Created by [Rosie](https://github.com/PBOwner) with <3
nav:
- Home: index.md
- DiscordModals: DiscordModals.md
site_name: DiscordModals's Documentation
site_url: https://docs.prismbot.icu/DiscordModals/
theme:
  name: dracula
use_directory_urls: false
