extra:
  footer: Created by [Rosie](https://github.com/PBOwner) with <3
nav:
- Home: index.md
- Lock: Lock.md
site_name: Lock's Documentation
site_url: https://docs.prismbot.icu/Lock/
theme:
  name: dracula
use_directory_urls: false
