extra:
  footer: Created by [Rosie](https://github.com/PBOwner) with <3
nav:
- Home: index.md
- NameChanger: NameChanger.md
site_name: NameChanger's Documentation
site_url: https://docs.prismbot.icu/NameChanger/
theme:
  name: dracula
use_directory_urls: false
