extra:
  footer: Created by [Rosie](https://github.com/PBOwner) with <3
nav:
- Home: index.md
- Cooldown: Cooldown.md
site_name: Cooldown's Documentation
site_url: https://docs.prismbot.icu/Cooldown/
theme:
  name: dracula
use_directory_urls: false
