extra:
  footer: Created by [Rosie](https://github.com/PBOwner) with <3
nav:
- Home: index.md
- Permissions: Permissions.md
site_name: Permissions's Documentation
site_url: https://docs.prismbot.icu/Permissions/
theme:
  name: dracula
use_directory_urls: false
