extra:
  footer: Created by [Rosie](https://github.com/PBOwner) with <3
nav:
- Home: index.md
- Color: Color.md
site_name: Color's Documentation
site_url: https://docs.prismbot.icu/Color/
theme:
  name: dracula
use_directory_urls: false
