extra:
  footer: Created by [Rosie](https://github.com/PBOwner) with <3
nav:
- Home: index.md
- CustomHelp: CustomHelp.md
site_name: CustomHelp's Documentation
site_url: https://docs.prismbot.icu/CustomHelp/
theme:
  name: dracula
use_directory_urls: false
