extra:
  footer: Created by [Rosie](https://github.com/PBOwner) with <3
nav:
- Home: index.md
- CaseInsensitive: CaseInsensitive.md
site_name: CaseInsensitive's Documentation
site_url: https://docs.prismbot.icu/CaseInsensitive/
theme:
  name: dracula
use_directory_urls: false
