extra:
  footer: Created by [Rosie](https://github.com/PBOwner) with <3
nav:
- Home: index.md
- FeatureRequest: FeatureRequest.md
site_name: FeatureRequest's Documentation
site_url: https://docs.prismbot.icu/FeatureRequest/
theme:
  name: dracula
use_directory_urls: false
