extra:
  footer: Created by [Rosie](https://github.com/PBOwner) with <3
nav:
- Home: index.md
- AltMarker: AltMarker.md
site_name: AltMarker's Documentation
site_url: https://docs.prismbot.icu/AltMarker/
theme:
  name: dracula
use_directory_urls: false
