extra:
  footer: Created by [Rosie](https://github.com/PBOwner) with <3
nav:
- Home: index.md
- AdvancedBlacklist: AdvancedBlacklist.md
site_name: AdvancedBlacklist's Documentation
site_url: https://docs.prismbot.icu/AdvancedBlacklist/
theme:
  name: dracula
use_directory_urls: false
