extra:
  footer: Created by [Rosie](https://github.com/PBOwner) with <3
nav:
- Home: index.md
- MemberCount: MemberCount.md
site_name: MemberCount's Documentation
site_url: https://docs.prismbot.icu/MemberCount/
theme:
  name: dracula
use_directory_urls: false
