extra:
  footer: Created by [Rosie](https://github.com/PBOwner) with <3
nav:
- Home: index.md
- VrtUtils: VrtUtils.md
site_name: VrtUtils's Documentation
site_url: https://docs.prismbot.icu/VrtUtils/
theme:
  name: dracula
use_directory_urls: false
