extra:
  footer: Created by [Rosie](https://github.com/PBOwner) with <3
nav:
- Home: index.md
- Jokes: Jokes.md
site_name: Jokes's Documentation
site_url: https://docs.prismbot.icu/Jokes/
theme:
  name: dracula
use_directory_urls: false
