extra:
  footer: Created by [Rosie](https://github.com/PBOwner) with <3
nav:
- Home: index.md
- Hider: Hider.md
site_name: Hider's Documentation
site_url: https://docs.prismbot.icu/Hider/
theme:
  name: dracula
use_directory_urls: false
